-- Updated schema for food_servings (with fdc_id)
CREATE TABLE public.food_servings (
    id uuid DEFAULT gen_random_uuid() NOT NULL,
    fdc_id bigint,
    food_name text NOT NULL,
    serving_description text,
    calories numeric(8,2),
    protein_g numeric(6,2),
    carbs_g numeric(6,2),
    fat_g numeric(6,2),
    fiber_g numeric(6,2),
    sugar_g numeric(6,2),
    sodium_mg numeric(8,2),
    calcium_mg numeric(8,2) DEFAULT 0.00,
    iron_mg numeric(8,2) DEFAULT 0.00,
    vitamin_c_mg numeric(8,2) DEFAULT 0.00,
    potassium_mg numeric(8,2) DEFAULT 0.00,
    vitamin_a_mcg numeric(8,2) DEFAULT 0.00,
    vitamin_e_mg numeric(8,2) DEFAULT 0.00,
    vitamin_k_mcg numeric(8,2) DEFAULT 0.00,
    thiamin_mg numeric(8,2),
    riboflavin_mg numeric(8,2),
    niacin_mg numeric(8,2),
    vitamin_b6_mg numeric(8,2),
    folate_mcg numeric(8,2),
    vitamin_b12_mcg numeric(8,2),
    magnesium_mg numeric(8,2),
    phosphorus_mg numeric(8,2),
    zinc_mg numeric(8,2),
    copper_mg numeric(8,2),
    selenium_mcg numeric(8,2),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now(),
    brand text,
    category text,
    data_sources text DEFAULT 'user_input'::text,
    quality_score integer DEFAULT 0,
    enrichment_status text DEFAULT 'pending'::text,
    last_enrichment timestamp with time zone,
    is_verified boolean DEFAULT false,
    source text DEFAULT 'user_input'::text,
    pdcaas_score numeric(3,2) DEFAULT 0.00
);
