/**
 * @fileoverview Schedule Routine Edge Function
 * @description Supabase Edge Function that creates Google Calendar events for trainer-client sessions
 * and logs them to the scheduled_routines table. Handles OAuth token refresh and client invitation.
 * 
 * @author Felony Fitness Development Team
 * @version 1.0.0
 * @since 2025-11-02
 * 
 * @requires Deno
 * @requires Supabase
 * @requires Google Calendar API
 * 
 * Request Body:
 * - client_id: UUID of the client
 * - program_routine_id: UUID of the program routine template
 * - start_time: ISO timestamp for session start
 * - end_time: ISO timestamp for session end
 * - routine_name: Display name for the routine
 * 
 * @example
 * // POST to /functions/v1/schedule-routine
 * {
 *   "client_id": "uuid-here",
 *   "program_routine_id": "uuid-here", 
 *   "start_time": "2025-11-03T10:00:00Z",
 *   "end_time": "2025-11-03T11:00:00Z",
 *   "routine_name": "Full Body A"
 * }
 */

import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

interface ScheduleRequest {
  client_id: string;
  program_routine_id: string;
  start_time: string;
  end_time: string;
  routine_name: string;
}

interface GoogleTokenResponse {
  access_token: string;
  expires_in: number;
  token_type: string;
}

interface GoogleCalendarEvent {
  id: string;
  summary: string;
  start: { dateTime: string };
  end: { dateTime: string };
  attendees?: Array<{ email: string }>;
}

/**
 * Refresh Google OAuth access token using refresh token
 */
async function refreshGoogleToken(refreshToken: string): Promise<string> {
  const tokenUrl = 'https://oauth2.googleapis.com/token';
  
  const body = new URLSearchParams({
    client_id: Deno.env.get('GOOGLE_CLIENT_ID')!,
    client_secret: Deno.env.get('GOOGLE_CLIENT_SECRET')!,
    refresh_token: refreshToken,
    grant_type: 'refresh_token'
  });

  const response = await fetch(tokenUrl, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
    },
    body: body.toString(),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Failed to refresh Google token: ${error}`);
  }

  const tokenData: GoogleTokenResponse = await response.json();
  return tokenData.access_token;
}

/**
 * Create Google Calendar event with client as attendee
 */
async function createGoogleCalendarEvent(
  accessToken: string,
  eventData: {
    summary: string;
    start_time: string;
    end_time: string;
    client_email: string;
  }
): Promise<string> {
  const calendarUrl = 'https://www.googleapis.com/calendar/v3/calendars/primary/events';
  
  const eventBody = {
    summary: eventData.summary,
    start: {
      dateTime: eventData.start_time,
      timeZone: 'UTC'
    },
    end: {
      dateTime: eventData.end_time,
      timeZone: 'UTC'
    },
    attendees: [
      { email: eventData.client_email }
    ],
    sendUpdates: 'all', // Notify all attendees
    description: `Scheduled workout session: ${eventData.summary}\n\nGenerated by Felony Fitness App`
  };

  const response = await fetch(calendarUrl, {
    method: 'POST',
    headers: {
      'Authorization': `Bearer ${accessToken}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(eventBody),
  });

  if (!response.ok) {
    const error = await response.text();
    throw new Error(`Failed to create Google Calendar event: ${error}`);
  }

  const eventResponse: GoogleCalendarEvent = await response.json();
  return eventResponse.id;
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response('ok', { headers: corsHeaders })
  }

  try {
    // Initialize Supabase client
    const supabaseClient = createClient(
      Deno.env.get('SUPABASE_URL') ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? '',
      {
        global: {
          headers: { Authorization: req.headers.get('Authorization')! },
        },
      }
    )

    // Step 1: Get trainer's auth from request
    const authHeader = req.headers.get('Authorization');
    if (!authHeader) {
      throw new Error('Authorization header required');
    }

    const { data: { user }, error: userError } = await supabaseClient.auth.getUser();
    if (userError || !user) {
      throw new Error('Invalid authentication');
    }
    
    const trainerId = user.id;

    // Parse request body
    const requestData: ScheduleRequest = await req.json();
    const { client_id, program_routine_id, start_time, end_time, routine_name } = requestData;

    // Validate required fields
    if (!client_id || !program_routine_id || !start_time || !end_time || !routine_name) {
      throw new Error('Missing required fields');
    }

    // Step 2: Get trainer's Google refresh token
    const { data: trainerProfile, error: trainerError } = await supabaseClient
      .from('user_profiles')
      .select('google_refresh_token')
      .eq('id', trainerId)
      .single();

    if (trainerError || !trainerProfile?.google_refresh_token) {
      throw new Error('Trainer Google authentication not found. Please reconnect your Google account.');
    }

    // Step 3: Get new access token
    const accessToken = await refreshGoogleToken(trainerProfile.google_refresh_token);

    // Step 4: Get client's email
    const { data: clientProfile, error: clientError } = await supabaseClient
      .from('user_profiles')
      .select('email')
      .eq('id', client_id)
      .single();

    if (clientError || !clientProfile?.email) {
      throw new Error('Client profile not found');
    }

    // Step 5: Create Google Calendar event
    const googleEventId = await createGoogleCalendarEvent(accessToken, {
      summary: routine_name,
      start_time,
      end_time,
      client_email: clientProfile.email
    });

    // Step 6: Save to our database
    const { data: scheduledRoutine, error: insertError } = await supabaseClient
      .from('scheduled_routines')
      .insert({
        trainer_id: trainerId,
        client_id,
        program_routine_id,
        google_calendar_event_id: googleEventId,
        start_time,
        end_time,
        routine_name,
        reminder_sent: false
      })
      .select()
      .single();

    if (insertError) {
      throw new Error(`Failed to save scheduled routine: ${insertError.message}`);
    }

    // Step 7: Return success
    return new Response(
      JSON.stringify({
        success: true,
        message: 'Routine scheduled successfully',
        data: {
          scheduled_routine_id: scheduledRoutine.id,
          google_event_id: googleEventId,
          client_email: clientProfile.email
        }
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 200,
      }
    );

  } catch (error) {
    console.error('Schedule routine error:', error);

    return new Response(
      JSON.stringify({
        success: false,
        error: error.message,
        message: 'Failed to schedule routine'
      }),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
        status: 400,
      }
    );
  }
})

/* To deploy this function, run:
deno run --allow-net supabase/functions/schedule-routine/index.ts
*/